apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: HCP Terraform Runner

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: string
        default: dev
      operation:
        description: Terraform operation
        required: true
        type: string
        default: plan
      run_infracost:
        description: Run Infracost cost estimation
        required: false
        type: boolean
        default: false

jobs:
  terraform:
    steps:
      - name: Checkout demo repository
        uses: cloudbees-io/checkout@v2

      - name: Checkout platform policies
        uses: cloudbees-io/checkout@v2
        with:
          repository: https://github.com/squidstack/platform-policies
          ref: main
          path: platform-policies

      - name: OPA policy validation
        id: opa
        uses: docker://alpine:3.20
        shell: sh
        run: |
          set -e
          apk add --no-cache curl tar

          echo "Installing Conftest (OPA)..."
          curl -L https://github.com/open-policy-agent/conftest/releases/download/v0.49.1/conftest_0.49.1_Linux_x86_64.tar.gz | tar xz
          chmod +x conftest

          echo ""
          echo "=== OPA Policy Validation ==="
          echo "Policy source: squidstack/platform-policies@main"
          echo "Validating Terraform plan against governance policies..."
          echo ""

          # Run conftest against example plan from policy repo
          if ./conftest test platform-policies/examples/terraform/plan.json -p platform-policies/policies/terraform/; then
            OPA_STATUS="passed"
            OPA_SUMMARY="All policy checks passed"
            echo ""
            echo "✅ All policy checks passed"
          else
            OPA_STATUS="failed"
            OPA_SUMMARY="Policy violations detected"
            echo ""
            echo "❌ Policy violations detected"
            exit 1
          fi

          printf '%s' "${OPA_STATUS}" > "$CLOUDBEES_OUTPUTS/OPA_STATUS"
          printf '%s' "${OPA_SUMMARY}" > "$CLOUDBEES_OUTPUTS/OPA_SUMMARY"

      - name: Infracost cost estimation
        id: infracost
        uses: docker://alpine:3.20
        shell: sh
        env:
          RUN_INFRACOST: ${{ inputs.run_infracost }}
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: |
          set -e

          # Check if Infracost is enabled
          if [ "${RUN_INFRACOST}" != "true" ]; then
            echo "⏭️  Infracost skipped (disabled by user)"
            printf 'skipped' > "$CLOUDBEES_OUTPUTS/INFRACOST_STATUS"
            printf 'N/A' > "$CLOUDBEES_OUTPUTS/MONTHLY_COST"
            exit 0
          fi

          # Check if API key is available
          if [ -z "${INFRACOST_API_KEY}" ]; then
            echo "⚠️  INFRACOST_API_KEY not configured"
            echo "Infracost check will be skipped"
            printf 'skipped' > "$CLOUDBEES_OUTPUTS/INFRACOST_STATUS"
            printf 'N/A' > "$CLOUDBEES_OUTPUTS/MONTHLY_COST"
            exit 0
          fi

          apk add --no-cache curl tar jq

          echo "Installing Infracost..."
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

          echo ""
          echo "=== Infrastructure Cost Estimation ==="
          echo "Analyzing: ${{ inputs.environment }} environment"
          echo "Path: ./terraform"

          # Run infracost breakdown
          if /usr/local/bin/infracost breakdown \
            --path ./terraform \
            --format json > /tmp/cost.json 2>&1; then

            # Validate JSON before parsing
            if ! jq empty /tmp/cost.json 2>/dev/null; then
              echo "⚠️  Infracost did not return valid JSON"
              echo "This is expected for null_resource which has no cost data"
              printf 'no_cost_data' > "$CLOUDBEES_OUTPUTS/INFRACOST_STATUS"
              printf '0.00' > "$CLOUDBEES_OUTPUTS/MONTHLY_COST"
            else
              MONTHLY_COST_RAW="$(jq -r '.totalMonthlyCost // empty' /tmp/cost.json)"

              if [ -n "${MONTHLY_COST_RAW}" ] && [ "${MONTHLY_COST_RAW}" != "null" ]; then
                MONTHLY_COST="$(printf "%.2f" "${MONTHLY_COST_RAW}")"

                echo ""
                echo "Monthly cost estimate: \$${MONTHLY_COST}"
                echo ""

                # Display breakdown
                /usr/local/bin/infracost breakdown --path ./terraform || true

                printf '%s' "${MONTHLY_COST}" > "$CLOUDBEES_OUTPUTS/MONTHLY_COST"
                printf 'ok' > "$CLOUDBEES_OUTPUTS/INFRACOST_STATUS"

                echo "💰 Cost calculated: \$${MONTHLY_COST}/month"
              else
                echo "⚠️  Could not extract cost from Infracost output"
                printf 'no_cost_data' > "$CLOUDBEES_OUTPUTS/INFRACOST_STATUS"
                printf '0.00' > "$CLOUDBEES_OUTPUTS/MONTHLY_COST"
              fi
            fi
          else
            echo "⚠️  Infracost execution failed"
            printf 'error' > "$CLOUDBEES_OUTPUTS/INFRACOST_STATUS"
            printf 'N/A' > "$CLOUDBEES_OUTPUTS/MONTHLY_COST"
          fi

      - name: Validate cost budget
        if: ${{ steps.infracost.outputs.INFRACOST_STATUS == 'ok' }}
        uses: docker://alpine:3.20
        shell: sh
        env:
          MONTHLY_COST: ${{ steps.infracost.outputs.MONTHLY_COST }}
          BUDGET_THRESHOLD: ${{ vars.INFRA_COST_BUDGET_THRESHOLD || '100' }}
        run: |
          set -e

          echo "=========================================="
          echo "Cost Budget Validation"
          echo "=========================================="
          echo ""
          echo "Monthly cost estimate: \$${MONTHLY_COST}"
          echo "Budget threshold: \$${BUDGET_THRESHOLD}"
          echo ""

          if awk "BEGIN {exit !($MONTHLY_COST > $BUDGET_THRESHOLD)}"; then
            echo "❌ COST VALIDATION FAILED"
            echo ""
            echo "Estimated cost (\$${MONTHLY_COST}/month) exceeds budget threshold (\$${BUDGET_THRESHOLD}/month)"
            exit 1
          fi

          echo "✅ COST VALIDATION PASSED"
          echo "Estimated cost (\$${MONTHLY_COST}/month) is within budget (\$${BUDGET_THRESHOLD}/month)"

      - name: Run HCP Terraform Operation
        id: hcp
        uses: guru-actions/hcp-terraform@main
        with:
          environment: ${{ inputs.environment }}
          operation: ${{ inputs.operation }}
          workspace: hcp-${{ inputs.environment }}
          stub_mode: true
          vcs_repo: squidstack/hcp-terraform-demo
          vcs_branch: main
          commit_sha: ${{ cloudbees.scm.sha }}
          opa_status: ${{ steps.opa.outputs.OPA_STATUS }}
          monthly_cost: ${{ steps.infracost.outputs.MONTHLY_COST }}

      - name: Display Results
        uses: docker://alpine:3.20
        shell: sh
        env:
          RUN_ID: ${{ steps.hcp.outputs.run_id }}
          RUN_URL: ${{ steps.hcp.outputs.run_url }}
          STATUS: ${{ steps.hcp.outputs.status }}
          RUN_STATUS: ${{ steps.hcp.outputs.run_status }}
          WORKSPACE: ${{ steps.hcp.outputs.workspace_name }}
          TFC_ORG: ${{ steps.hcp.outputs.tfc_org }}
          VCS_REPO: ${{ steps.hcp.outputs.vcs_repo }}
          VCS_BRANCH: ${{ steps.hcp.outputs.vcs_branch }}
          COMMIT_SHA: ${{ steps.hcp.outputs.vcs_commit_sha }}
          OPA_STATUS: ${{ steps.opa.outputs.OPA_STATUS }}
          INFRACOST_STATUS: ${{ steps.infracost.outputs.INFRACOST_STATUS }}
          MONTHLY_COST: ${{ steps.infracost.outputs.MONTHLY_COST }}
        run: |
          echo "=== HCP Terraform Run Results ==="
          echo "Organization: ${TFC_ORG}"
          echo "Workspace: ${WORKSPACE}"
          echo "Run ID: ${RUN_ID}"
          echo "Status: ${STATUS}"
          echo "Run Status: ${RUN_STATUS}"
          echo "Run URL: ${RUN_URL}"
          echo ""
          echo "=== VCS Configuration ==="
          echo "Repository: ${VCS_REPO}"
          echo "Branch: ${VCS_BRANCH}"
          echo "Commit SHA: ${COMMIT_SHA}"
          echo ""
          echo "=== Pre-flight Governance ==="
          echo "OPA Policy: ${OPA_STATUS}"
          echo "Infracost: ${INFRACOST_STATUS}"
          printf 'Monthly Cost: $%s\n' "${MONTHLY_COST}"

      - name: Publish Evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## HCP Terraform VCS-Connected Run

            ### Pre-flight Governance (CloudBees Unify)

            | Check | Status | Details |
            |-------|--------|---------|
            | **OPA Policy** | ${{ steps.opa.outputs.OPA_STATUS == 'passed' && '✅ Passed' || '❌ Failed' }} | ${{ steps.opa.outputs.OPA_SUMMARY }} |
            | **Policy Source** | External Repository | `squidstack/platform-policies@main` |
            | **Infracost** | ${{ steps.infracost.outputs.INFRACOST_STATUS == 'ok' && '✅ Analyzed' || steps.infracost.outputs.INFRACOST_STATUS == 'skipped' && '⏭️ Skipped' || steps.infracost.outputs.INFRACOST_STATUS == 'no_cost_data' && 'ℹ️ No Cost Data' || '⚠️ Error' }} | ${{ steps.infracost.outputs.INFRACOST_STATUS == 'no_cost_data' && 'Resources have no cost (e.g., null_resource)' || steps.infracost.outputs.MONTHLY_COST != 'N/A' && format('Cost: ${0}/month (Budget: ${1}/month)', steps.infracost.outputs.MONTHLY_COST, vars.INFRA_COST_BUDGET_THRESHOLD || '100') || 'Not run' }} |

            **Governance Model:** Policies are managed separately by the platform/security team in `squidstack/platform-policies`. This ensures centralized policy management with clear ownership boundaries.

            ---

            ### Terraform Cloud Configuration

            | Field | Value |
            |-------|-------|
            | **Organization** | ${{ steps.hcp.outputs.tfc_org }} |
            | **Workspace** | ${{ steps.hcp.outputs.workspace_name }} |
            | **Run ID** | `${{ steps.hcp.outputs.run_id }}` |
            | **Run URL** | [${{ steps.hcp.outputs.run_id }}](${{ steps.hcp.outputs.run_url }}) |
            | **Run Status** | ${{ steps.hcp.outputs.run_status }} |
            | **Status** | ${{ steps.hcp.outputs.status }} |

            ### VCS Integration

            | Field | Value |
            |-------|-------|
            | **Repository** | `${{ steps.hcp.outputs.vcs_repo }}` |
            | **Branch** | `${{ steps.hcp.outputs.vcs_branch }}` |
            | **Commit SHA** | `${{ steps.hcp.outputs.vcs_commit_sha }}` |

            ### Execution Details

            | Field | Value |
            |-------|-------|
            | **Environment** | ${{ inputs.environment }} |
            | **Operation** | ${{ inputs.operation }} |

            ### Plan Summary

            ```json
            ${{ steps.hcp.outputs.summary_json }}
            ```

            ---

            *VCS-Connected Workspace Model: Terraform Cloud pulls configuration from Git, CloudBees Unify orchestrates runs with external governance policies*
          format: MARKDOWN
