apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: HCP Terraform Runner

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: string
        default: dev
      operation:
        description: Terraform operation
        required: true
        type: string
        default: plan

jobs:
  terraform:
    steps:
      - name: Checkout demo repository
        uses: cloudbees-io/checkout@v2

      - name: Run HCP Terraform Operation
        id: hcp
        uses: guru-actions/hcp-terraform@main
        with:
          environment: ${{ inputs.environment }}
          operation: ${{ inputs.operation }}
          workspace: hcp-${{ inputs.environment }}
          stub_mode: true
          vcs_repo: squidstack/hcp-terraform-demo
          vcs_branch: main
          commit_sha: ${{ cloudbees.scm.sha }}

      - name: Display Results
        uses: docker://alpine:3.20
        shell: sh
        env:
          RUN_ID: ${{ steps.hcp.outputs.run_id }}
          RUN_URL: ${{ steps.hcp.outputs.run_url }}
          STATUS: ${{ steps.hcp.outputs.status }}
          RUN_STATUS: ${{ steps.hcp.outputs.run_status }}
          WORKSPACE: ${{ steps.hcp.outputs.workspace_name }}
          TFC_ORG: ${{ steps.hcp.outputs.tfc_org }}
          VCS_REPO: ${{ steps.hcp.outputs.vcs_repo }}
          VCS_BRANCH: ${{ steps.hcp.outputs.vcs_branch }}
          COMMIT_SHA: ${{ steps.hcp.outputs.vcs_commit_sha }}
        run: |
          echo "=== HCP Terraform Run Results ==="
          echo "Organization: ${TFC_ORG}"
          echo "Workspace: ${WORKSPACE}"
          echo "Run ID: ${RUN_ID}"
          echo "Status: ${STATUS}"
          echo "Run Status: ${RUN_STATUS}"
          echo "Run URL: ${RUN_URL}"
          echo ""
          echo "=== VCS Configuration ==="
          echo "Repository: ${VCS_REPO}"
          echo "Branch: ${VCS_BRANCH}"
          echo "Commit SHA: ${COMMIT_SHA}"

      - name: Publish Evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## HCP Terraform VCS-Connected Run

            ### Terraform Cloud Configuration

            | Field | Value |
            |-------|-------|
            | **Organization** | ${{ steps.hcp.outputs.tfc_org }} |
            | **Workspace** | ${{ steps.hcp.outputs.workspace_name }} |
            | **Run ID** | `${{ steps.hcp.outputs.run_id }}` |
            | **Run URL** | [${{ steps.hcp.outputs.run_id }}](${{ steps.hcp.outputs.run_url }}) |
            | **Run Status** | ${{ steps.hcp.outputs.run_status }} |
            | **Status** | ${{ steps.hcp.outputs.status }} |

            ### VCS Integration

            | Field | Value |
            |-------|-------|
            | **Repository** | `${{ steps.hcp.outputs.vcs_repo }}` |
            | **Branch** | `${{ steps.hcp.outputs.vcs_branch }}` |
            | **Commit SHA** | `${{ steps.hcp.outputs.vcs_commit_sha }}` |

            ### Execution Details

            | Field | Value |
            |-------|-------|
            | **Environment** | ${{ inputs.environment }} |
            | **Operation** | ${{ inputs.operation }} |

            ### Plan Summary

            ```json
            ${{ steps.hcp.outputs.summary_json }}
            ```

            ---

            *VCS-Connected Workspace Model: Terraform Cloud pulls configuration from Git, CloudBees Unify orchestrates runs*
          format: MARKDOWN
